# Generated by Django 4.2.7 on 2023-11-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_like",
            field=models.BooleanField(),
        ),
    ]
