# Generated by Django 4.2.7 on 2023-11-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_alter_article_is_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_like",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
